# Generated by Django 5.0.1 on 2024-01-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=10)),
                ('use_bio', models.CharField(max_length=20)),
                ('user_image', models.ImageField(upload_to='')),
                ('user_portfolio', models.URLField()),
                ('generation_number', models.IntegerField()),
            ],
        ),
    ]
