# Generated by Django 5.0.1 on 2024-01-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='use_bio',
            new_name='user_bio',
        ),
        migrations.RemoveField(
            model_name='people',
            name='user_portfolio',
        ),
        migrations.AddField(
            model_name='people',
            name='user_portfolio1',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='people',
            name='user_portfolio2',
            field=models.URLField(default=''),
        ),
    ]
