# Generated by Django 5.0.1 on 2024-01-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.CharField(max_length=500)),
                ('motivation', models.CharField(max_length=500)),
                ('project_experience', models.CharField(max_length=800)),
                ('study_experience', models.CharField(max_length=700)),
                ('submit_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
